maps/si_caldera.loc
maps/si_caldera.txt
maps/si_caldera.res
overviews/si_caldera.tga
overviews/si_caldera.txt
sound/ambience/lava.wav
sound/ambience/lowboom.wav
sound/ambience/rumble.wav
sound/misc/r_tele3.wav
sound/misc/r_tele5.wavr