maps/si_organic.res
maps/si_organic.txt
maps/vgui/si_organic_1.tga
maps/vgui/si_organic_2.tga
maps/vgui/si_organic_3.tga
gfx/env/forest256_bk.tga
gfx/env/forest256_dn.tga
gfx/env/forest256_ft.tga
gfx/env/forest256_lf.tga
gfx/env/forest256_rt.tga
gfx/env/forest256_up.tga
models/arnie.mdl
si_organic.wad
