gfx/env/null_plainsky256_up.tga
gfx/env/null_plainsky256_dn.tga
gfx/env/null_plainsky256_lf.tga
gfx/env/null_plainsky256_rt.tga
gfx/env/null_plainsky256_ft.tga
gfx/env/null_plainsky256_bk.tga
maps/vgui/si_overfloater_1.tga
maps/vgui/si_overfloater_2.tga
maps/vgui/si_overfloater_chum.tga
maps/vgui/si_overfloater_labs.tga
maps/si_overfloater.loc
maps/si_overfloater.txt
maps/si_overfloater.res
maps/si_overfloater_extra.txt
overviews/si_overfloater.bmp
overviews/si_overfloater.txt
